name: Snyk
on:
  push:
    branches: [ master ]
jobs:
  security:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Run npm install on Core
      run: npm ci
      working-directory: ./core

    - name: Run npm intall on Tracker
      run: npm ci

    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      with:
        command: monitor
        args: --all-projects
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
