export const plugins = {
  performanceTiming: false,
  gaCookies: false,
  geolocation: false,
  optimizelyX: false,
  clientHints: false,
  consent: false,
  linkClickTracking: false,
  formTracking: false,
  errorTracking: false,
  timezone: false,
  ecommerce: false,
  enhancedEcommerce: false,
  adTracking: false,
  siteTracking: false,
  optimizely: false,
  parrable: false,
  browserFeatures: false,
};
