export const plugins = {
  performanceTiming: true,
  gaCookies: true,
  geolocation: true,
  optimizely: true,
  optimizelyX: true,
  parrable: true,
  clientHints: true,
  gdpr: true,
  linkClickTracking: true,
  formTracking: true,
  errorTracking: true,
  browserFeatures: true,
  timezone: true,
};
