export const plugins = {
  performanceTiming: true,
  gaCookies: true,
  geolocation: true,
  optimizelyX: true,
  clientHints: true,
  consent: true,
  linkClickTracking: true,
  formTracking: true,
  errorTracking: true,
  timezone: true,
  ecommerce: true,
  enhancedEcommerce: true,
  adTracking: true,
  siteTracking: true,
  optimizely: false,
  parrable: false,
  browserFeatures: false,
};
